Import("env_test")


sources_test = Glob("./*.cc")
Import("objs_curve")

prg_test = env_test.Program(
    "test"
  , sources_test + objs_curve
  )

run_test = env_test.Alias("test", prg_test, prg_test[0].get_abspath())
AlwaysBuild(run_test)
