Import("env")


libs_test = [
  "boost_unit_test_framework"
  ]


env_test = env.Clone()
env_test.Append(
    LIBS     = libs_test
  )


sources_test = Glob("./*.cc")

Import("objs_curve")


test = env_test.Program(
    "test"
  , sources_test + objs_curve
  )

Export("test")
