Import(["env", "env_merger", "env_mpi"])


sources_curve = [
    "block_iterator.cc"
  , "curve.cc"
  , "curve_iterator.cc"
  , "fq_element_table.cc"
  , "isogeny_representative_store.cc"
  , "opencl_interface.cc"
  , "reduction_table.cc"
  , "single_curve_fp.cc"
  ]

objs_curve = [ env.Object(s) for s in sources_curve ]
Export("objs_curve")


prg_single = env.Program(
    "executable/single"
  , [ "excutables/single.cc" ] + objs_curve
  )
env.InstallAs(env["prefix"] + "/bin/single", prg_single)
Alias("single", prg_single)


prg_legacy = env.Program(
    "executable/legacy"
  , [ "excutables/legacy.cc", "isogeny_count_store.cc" ] + objs_curve
  )
env.InstallAs(env["prefix"] + "/bin/legacy", prg_legacy)
Alias("legacy", prg_legacy)


prg_merger = env_merger.Program(
    "executable/merger"
  , [ "excutables/merge_isogeny_representatives.cc" ]
    + objs_curve
  )
env_merger.InstallAs(env["prefix"] + "/bin/merger", prg_merger)
Alias("merger", prg_merger)


prg_mpi = env_mpi.Program(
    "executable/mpi"
  , [ "excutables/mpi.cc"
    , "mpi/worker_pool.cc"
    , "mpi/config_node.cc"
    ]
    + objs_curve
  )
env_mpi.InstallAs(env["prefix"] + "/bin/mpi", prg_mpi)
Alias("mpi", prg_mpi)
